import type { Metadata } from "next";
import "./globals.css";



export const metadata: Metadata = {
  title: "Jedibasil | Works",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body data-theme={"dark"}>{children}</body>
    </html>
  );
}
